[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && CI=false npm run build"]

[start]
cmd = "cd frontend && npx serve -s build -l $PORT"