[build]
builder = "nixpacks"
nixpacksPlan = { providers = ["node"] }
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npm install -g serve && serve -s build -l $PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"