[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npx serve -s build -l $PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"