[build]
builder = "nixpacks"
buildCommand = "npm install --prefix frontend && npm run build --prefix frontend"

[deploy]
startCommand = "npx serve frontend/build -l $PORT"
restartPolicyType = "on_failure"