[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && CI=false npm run build"

[deploy]
startCommand = "cd frontend && npx serve -s build -l $PORT"
restartPolicyType = "on_failure"