services:
  # Backend API
  - type: web
    name: lpdp-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://scldp-frontend.onrender.com
      - key: HOST
        value: 0.0.0.0

  # Frontend Static Site
  - type: web
    name: lpdp-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://scldp-backend.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production