services:
  - type: web
    name: lpdp-backend-v2
    env: node
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY  
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: FRONTEND_URLS
        value: "http://localhost:3000,https://lpdp-frontend.onrender.com"