services:
  - type: web
    name: lpdp-capacitacion-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

databases:
  - name: lpdp-db
    databaseName: lpdp_capacitacion
    user: lpdp_admin
    region: oregon
    plan: starter
    postgresMajorVersion: 15
