services:
  - type: web
    name: scldp-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://scldp-frontend.onrender.com
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DB_POOL_SIZE
        value: 10
      - key: DB_MAX_OVERFLOW
        value: 20
      - key: DB_POOL_TIMEOUT
        value: 30
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_ACCESS_LOG
        value: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: SESSION_TIMEOUT
        value: 3600
