name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Deployment
      run: |
        echo "Forcing Render to detect services..."
        # This workflow file forces Render to re-scan the repository
        # and detect render.yaml and blueprint.yaml files

    - name: Notify Completion
      run: |
        echo "Deployment triggered. Check Render dashboard for new services:"
        echo "- lpdp-backend-v2 (Web Service)"
        echo "- lpdp-frontend-v2 (Static Site)"
